user:
  jay:
    username: 周杰伦
    password: 123456
  william:
    username: william
    password: 123456
  failure:
    username: failure
    password: 123456

url: http://110.41.4.36

mysql:
  db: trading_system
  host: 192.168.2.191
  password: william
  port: 3306