user:
  jay:
    username: 周杰伦
    password: 123456
  william:
    username: william
    password: 123456
  failure:
    username: failure
    password: 123456

url: http://110.41.4.36

mysql:
  db: trading_system
  host: 172.27.73.252
  password: william
  port: 3306

redis:
  host: 172.27.73.252
  port: 6379
  db: 0